# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PoC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PoC

  target 'PoCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PoCUITests' do
    inherit! :search_paths
    # Pods for testing
  end
 
  pod 'Firebase/Core'
  pod 'Firebase/Database'
 
end
